name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [ dev ]
    env:
      ENV: ${{ matrix.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Install TFLint
        uses: dtan4/setup-tflint@v1
        with:
          tflint_version: v0.53.0

      - name: Install tfsec
        run: curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip3 install checkov

      - name: Show environment and stack
        run: |
          make env-list
          make print-stack ENV=${{ matrix.env }}

      - name: Format (check)
        run: make fmt-check ENV=${{ matrix.env }}

      - name: Init
        run: make init ENV=${{ matrix.env }}

      - name: Validate
        run: make validate ENV=${{ matrix.env }}

      - name: TFLint
        run: make tflint ENV=${{ matrix.env }}

      - name: tfsec
        run: make tfsec ENV=${{ matrix.env }}

      - name: Checkov
        run: make checkov ENV=${{ matrix.env }}

  helm-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm lint
        run: make helm-lint

      - name: Helm template
        run: make helm-template
